apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bench-v07

# bases:
# - ../base

resources:
- ../base
# - redis-vector-db.yaml
# Add other resource files as needed

images:
  - name: embedding-image
    newName: opea/embedding-tei
    newTag: latest
  - name: retriever-image
    newName: opea/retriever-redis
    newTag: latest
  - name: reranking-image
    newName: opea/reranking-tei
    newTag: latest
  - name: llm-image
    newName: opea/llm-tgi
    newTag: latest
  - name: chatqna-image
    newName: opea/chatqna
    newTag: latest
  - name: dataprep-image
    newName: opea/dataprep-redis
    newTag: latest
