ARG UBUNTU_VER=22.04
FROM ubuntu:${UBUNTU_VER} as demo

ENV LANG C.UTF-8

RUN apt update
RUN  apt-get install npm -y 
RUN  apt install curl -y
RUN  npm install -g n && \
    n stable && \
    hash -r && \
    npm install -g npm@latest
WORKDIR /usr/app
COPY ./ /usr/app
RUN npm install
CMD ["nohup", "npm", "run", "dev", "&"]