apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: benchmarking

resources:
- ../../base_cpu
- ../../base_gaudi
images:
  - name: opea/embedding-tei:latest
    newName: opea/embedding-tei
    newTag: v0.7
  - name: opea/retriever-redis:latest
    newName: opea/retriever-redis
    newTag: v0.7-norerank
  - name: opea/reranking-tei:latest
    newName: opea/reranking-tei
    newTag: v0.7
  - name: opea/llm-tgi:latest
    newName: opea/llm-tgi
    newTag: v0.7
  - name: opea/chatqna:latest
    newName: opea/chatqna
    newTag: v0.7-norank
  - name: opea/dataprep-redis:latest
    newName: opea/dataprep-redis
    newTag: v0.7
